### PR TITLE
add Chinese support, and add  language chooser

### PR DESCRIPTION
**Pull request by abingoal**
The language chooser does not use `<select>`, but instead uses the `<a>` link. (this method is very poor, if we add more languages later, it will be very troublesome). A new `.language` style has been added to make the language chooser style more suitable with the whole site. If this way is not suitable, please tell me how to fix it.

### CODE REVIEW

**Comment by abingoal** [comment]
I think `vuepress` is a better solution at present.

**Comment by pleerock** [comment]
> I think vuepress is a better solution at present.

maybe, but not at the moment.

Can you came up with a better solution that doesn't duplicate exist components? Current solution doesn't look scalable =(

**Comment by abingoal** [comment]
> > I think vuepress is a better solution at present.
> 
> maybe, but not at the moment.
> 
> Can you came up with a better solution that doesn't duplicate exist components? Current solution doesn't look scalable =(

All right,I will try to modify it again.

**Comment by abingoal** [comment]
I modified the code for language chooser.
I daren't rashly modify the framework of the project, so I didn't use es6 module or commonJS to implement it. 
Instead, I used single file and referenced the language file in `index.html`. 
Loaded without using the module, the language files can't be lazy loaded, and there may be performance problems.
So if there is any need for improvement, please let me know to improve.

**Comment by pleerock** [comment]
looks much better 👍 Did you test everything? I'll merge it and it will go live instantly, did you check everything?)

**Comment by abingoal** [comment]
yeah, you can merge it. I have tested it on my Mac and it's working well. 
btw, there are also some Chinese typos and translations that are not accurate enough, I will modify it later.[zh-CN-doc](https://github.com/typeorm/typeorm/tree/master/docs/zh_CN)

**Comment by pleerock** [comment]
Thank you very much, it looks awesome!

The only concern I have is this language globe icon, can we change it and put language specific flag? Its not obvious what glob icon means in there, also its not obvious that it is a dropdown.

**Comment by abingoal** [comment]
At first I wanted to use this icon.
image
But I think it's not a round icon, it doesn't match the other icons, so I used the glob icon.

The following icons can be referenced:
image
image
image
But these icons are all square, I think we can change them to round.
If none of the above is appropriate, I can ask my colleagues to help me make a new one.

**Comment by pleerock** [comment]
I like a first one. Its okay if its not round.

**Pull request merged**
