### PR TITLE
feat: allow manually selecting dark color mode

### PR DESCRIPTION
**Pull request by ranjan-purbey**
Currently color-scheme for the site is derived directly from system color scheme. This PR adds a toggle button in the top-navbar to manually override the preferred color scheme and store the preference in local storage.

### CODE REVIEW

**Comment by ranjan-purbey** [comment]
Can this PR be merged or are there any further changes needed?

**Comment by pleerock** [comment]
oh I merged another PR and there are conflicts now...

**Comment by ranjan-purbey** [comment]
Would you be willing to merge this PR given I resolve the merge conflicts?

**Comment by pleerock** [comment]
yes sure, we need the toggle for sure.

**Comment by ranjan-purbey** [comment]
Hey @pleerock, I have fixed the conflicts

**Pull request merged**
